export const MainData = [
   { id: 1, name: "Minecraft", image: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b6/Minecraft_2024_cover_art.png/250px-Minecraft_2024_cover_art.png", platform: "PC", genre: "Sandbox", studio: "Mojang studio" },
  { id: 2, name: "Fortnite", image: "https://upload.wikimedia.org/wikipedia/en/a/ae/Fortnite_Save_The_World.jpg", platform: "PC", genre: "Shooter", studio: "Epic Games" },
  { id: 3, name: "Roblox", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Roblox_%282025%29_%28App_Icon%29.svg/250px-Roblox_%282025%29_%28App_Icon%29.svg.png", platform: "PC", genre: "Sandbox", studio: "Roblox Corporation" },
  { id: 4, name: "League of Legends", image: "https://cdn1.epicgames.com/offer/24b9b5e323bc40eea252a10cdd3b2f10/EGS_LeagueofLegends_RiotGames_S1_2560x1440-47eb328eac5ddd63ebd096ded7d0d5ab", platform: "PC", genre: "MOBA", studio: "Riot Games" },
  { id: 5, name: "Valorant", image: "https://mediaproxy.tvtropes.org/width/1200/https://static.tvtropes.org/pmwiki/pub/images/valo2.png", platform: "PC", genre: "Shooter", studio: "Riot Games" },
  { id: 6, name: "Overwatch 2", image: "https://upload.wikimedia.org/wikipedia/en/8/89/Overwatch_2_Steam_artwork.jpg", platform: "PC", genre: "Shooter", studio: "Blizzard Entertainment" },
  { id: 7, name: "Apex Legends", image: "https://upload.wikimedia.org/wikipedia/en/d/db/Apex_legends_cover.jpg", platform: "PC", genre: "Shooter", studio: "Respawn Entertainment" },
  { id: 8, name: "Cyberpunk 2077", image: "https://upload.wikimedia.org/wikipedia/en/9/9f/Cyberpunk_2077_box_art.jpg", platform: "PC", genre: "RPG", studio: "CD Projekt Red" },
  { id: 9, name: "The Witcher 3", image: "https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Witcher_3_cover_art.jpg/250px-Witcher_3_cover_art.jpg", platform: "PC", genre: "RPG", studio: "CD Projekt Red" },
  { id: 10, name: "Elden Ring", image: "https://e.snmc.io/lk/g/x/72f985e228a8cdf14a07809d91b8867e/9217773", platform: "PC", genre: "RPG", studio: "FromSoftware" },

  { id: 11, name: "GTA V", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMxzTVI2cKY0prxSJFuluZ7Wp7JCQ7c1V6zg&s", platform: "PC", genre: "Action", studio: "Rockstar Games" },
  { id: 12, name: "Red Dead Redemption 2", image: "https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg", platform: "Console", genre: "Adventure", studio: "Rockstar Games" },
  { id: 13, name: "God of War", image: "https://upload.wikimedia.org/wikipedia/fi/a/a1/God_of_War_Ragnar%C3%B6k.jpg", platform: "Console", genre: "Action", studio: "Santa Monica Studio" },
  { id: 14, name: "The Last of Us", image: "https://upload.wikimedia.org/wikipedia/en/8/86/The_Last_of_Us_Part_I_cover.jpg", platform: "Console", genre: "Adventure", studio: "Naughty Dog" },
  { id: 15, name: "Horizon Zero Dawn", image: "https://image.api.playstation.com/vulcan/ap/rnd/202409/2716/2cdf80a4335a032aac4302fd1a941cac3a0e237d6a1d1fe0.jpg", platform: "Console", genre: "RPG", studio: "Guerrilla Games" },
  { id: 16, name: "Spider-Man", image: "https://image.api.playstation.com/vulcan/img/rnd/202011/0714/At7kpPioyCSPENS5x6gHesjR.png", platform: "Console", genre: "Action", studio: "Insomniac Games" },
  { id: 17, name: "Halo Infinite", image: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1708091/capsule_616x353.jpg?t=1706638660", platform: "Console", genre: "Shooter", studio: "343 Industries" },
  { id: 18, name: "Gears 5", image: "https://store-images.s-microsoft.com/image/apps.10933.65494054591008504.4eae27ba-1cfe-4af2-950a-4af81f8cd22a.b5b2909d-8884-48d0-b25a-68d6518c9b73", platform: "Console", genre: "Shooter", studio: "The Coalition" },
  { id: 19, name: "Forza Horizon 5", image: "https://image.api.playstation.com/vulcan/ap/rnd/202502/0323/d808653f2c2453e79433628e31f673ef3976c6771d39228a.png", platform: "Console", genre: "Racing", studio: "Playground Games" },
  { id: 20, name: "Gran Turismo 7", image: "https://image.api.playstation.com/vulcan/ap/rnd/202202/2806/QDzid2jNv4e44kgumGXDCscF.png", platform: "Console", genre: "Racing", studio: "Polyphony Digital" },

  { id: 21, name: "Call of Duty: Warzone", image: "https://store-images.s-microsoft.com/image/apps.703.13739535057760905.34778648-088c-45a3-9d45-1117ca041901.c4d90513-3be4-4a22-9cd6-85a7ffa8df7f", platform: "PC", genre: "Shooter", studio: "Infinity Ward" },
  { id: 22, name: "Battlefield 2042", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUi3ICx3B6Ago_qbF3ga7dIHQdsS8pw_A2xA&s", platform: "PC", genre: "Shooter", studio: "DICE" },
  { id: 23, name: "Destiny 2", image: "https://upload.wikimedia.org/wikipedia/en/0/05/Destiny_2_%28artwork%29.jpg", platform: "PC", genre: "Shooter", studio: "Bungie" },
  { id: 24, name: "Doom Eternal", image: "https://image.api.playstation.com/vulcan/ap/rnd/202010/0114/ERNPc4gFqeRDG1tYQIfOKQtM.png", platform: "PC", genre: "Shooter", studio: "id Software" },
  { id: 25, name: "Rainbow Six Siege", image: "https://upload.wikimedia.org/wikipedia/en/4/47/Tom_Clancy%27s_Rainbow_Six_Siege_cover_art.jpg", platform: "PC", genre: "Shooter", studio: "Ubisoft Montreal" },

  { id: 26, name: "FC25", image: "https://image.api.playstation.com/vulcan/ap/rnd/202503/2520/f3c135f8ebdc50b782c6f5f02b27130b499e22847f05aee6.png", platform: "Console", genre: "Sports", studio: "EA Sports" },
  { id: 27, name: "NBA 2K25", image: "https://assets.2k.com/1a6ngf98576c/4J6ICvt6DPi4jnPvmc72MQ/9e64397d3459a717bea30b5e4d7772f2/N25-Announce-Homepage-Module_Two-Retail_Carousel-STD-425x535.jpg", platform: "Console", genre: "Sports", studio: "Visual Concepts" },
  { id: 28, name: "Madden NFL 25", image: "https://image.api.playstation.com/vulcan/ap/rnd/202406/1011/8bf6908bc4a21488c7bfa3bbf75ceca8f4c5137bafc136ae.png", platform: "Console", genre: "Sports", studio: "EA Sports" },
  { id: 29, name: "NHL 25", image: "https://image.api.playstation.com/vulcan/ap/rnd/202502/1121/610eff1a51d8f476882c8d388ae4c75c4e1d78f763cff116.png", platform: "Console", genre: "Fighting", studio: "EA Sports" },
  { id: 30, name: "UFC 5", image: "https://image.api.playstation.com/vulcan/ap/rnd/202309/0421/418704276d35ce02e8cb532c6ca3826cf866ad2ec66c0b17.png", platform: "Console", genre: "Fighting", studio: "EA Sports" },

  { id: 31, name: "Clash of Clans", image: "https://m.media-amazon.com/images/M/MV5BZTEyNjE0OGEtYmIwNS00NjQ4LTgzNTEtYWVmMzBkMmYxMGI0XkEyXkFqcGc@._V1_.jpg", platform: "Mobile", genre: "Strategy", studio: "Supercell" },
  { id: 32, name: "Clash Royale", image: "https://play-lh.googleusercontent.com/gnSC6s8-6Tjc4uhvDW7nfrSJxpbhllzYhgX8y374N1LYvWBStn2YhozS9XXaz1T_Pi2q", platform: "Mobile", genre: "Strategy", studio: "Supercell" },
  { id: 33, name: "Brawl Stars", image: "https://supercell.com/images/b524ca49e8549e5d3f5485452da7f26c/1050/cropped.webp", platform: "Mobile", genre: "Action", studio: "Supercell" },
  { id: 34, name: "PUBG Mobile", image: "https://play-lh.googleusercontent.com/9Q5je4kYh5EVvDLJSp20Vr6fFZB6qWAF0EtXj37o2h8yzD6vuvwa4fph83q7uIHkMQ7O", platform: "Mobile", genre: "Shooter", studio: "Tencent Games" },
  { id: 35, name: "Call of Duty Mobile", image: "https://via.placeholder.com/250x350?text=CoD+Mobile", platform: "Mobile", genre: "Shooter", studio: "Activision" },
  { id: 36, name: "Genshin Impact", image: "https://via.placeholder.com/250x350?text=Genshin+Impact", platform: "Mobile", genre: "RPG", studio: "miHoYo" },
  { id: 37, name: "Mobile Legends", image: "https://via.placeholder.com/250x350?text=Mobile+Legends", platform: "Mobile", genre: "MOBA", studio: "Moonton" },
  { id: 38, name: "Free Fire", image: "https://via.placeholder.com/250x350?text=Free+Fire", platform: "Mobile", genre: "Shooter", studio: "Garena" },
  { id: 39, name: "Asphalt 9", image: "https://via.placeholder.com/250x350?text=Asphalt+9", platform: "Mobile", genre: "Racing", studio: "Gameloft" },
  { id: 40, name: "Stumble Guys", image: "https://via.placeholder.com/250x350?text=Stumble+Guys", platform: "Mobile", genre: "Party", studio: "Kitka Games" },
  

  // 41–100: More PC / Console / Mobile Mix
    { id: 41, name: "Fall Guys", image: "https://via.placeholder.com/250x350?text=Fall+Guys", platform: "PC", genre: "Party", studio: "Mediatonic" },
  { id: 42, name: "Rocket League", image: "https://via.placeholder.com/250x350?text=Rocket+League", platform: "PC", genre: "Sports", studio: "Psyonix" },
  { id: 43, name: "Terraria", image: "https://via.placeholder.com/250x350?text=Terraria", platform: "PC", genre: "Adventure", studio: "Re-Logic" },
  { id: 44, name: "Stardew Valley", image: "https://via.placeholder.com/250x350?text=Stardew+Valley", platform: "PC", genre: "Simulation", studio: "ConcernedApe" },
  { id: 45, name: "Among Us", image: "https://via.placeholder.com/250x350?text=Among+Us", platform: "PC", genre: "Party", studio: "Innersloth" },
  { id: 46, name: "Palworld", image: "https://via.placeholder.com/250x350?text=Palworld", platform: "PC", genre: "Adventure", studio: "Pocketpair" },
  { id: 47, name: "ARK: Survival Evolved", image: "https://via.placeholder.com/250x350?text=ARK", platform: "PC", genre: "Survival", studio: "Studio Wildcard" },
  { id: 48, name: "Rust", image: "https://via.placeholder.com/250x350?text=Rust", platform: "PC", genre: "Survival", studio: "Facepunch Studios" },
  { id: 49, name: "Escape from Tarkov", image: "https://via.placeholder.com/250x350?text=Tarkov", platform: "PC", genre: "Shooter", studio: "Battlestate Games" },
  { id: 50, name: "Dota 2", image: "https://via.placeholder.com/250x350?text=Dota+2", platform: "PC", genre: "MOBA", studio: "Valve" },

  { id: 51, name: "Dead by Daylight", image: "https://via.placeholder.com/250x350?text=DBD", platform: "PC", genre: "Horror", studio: "Behaviour Interactive" },
  { id: 52, name: "Phasmophobia", image: "https://via.placeholder.com/250x350?text=Phasmophobia", platform: "PC", genre: "Horror", studio: "Kinetic Games" },
  { id: 53, name: "Outlast", image: "https://via.placeholder.com/250x350?text=Outlast", platform: "PC", genre: "Horror", studio: "Red Barrels" },
  { id: 54, name: "Resident Evil 4", image: "https://via.placeholder.com/250x350?text=RE4", platform: "Console", genre: "Horror", studio: "Capcom" },
  { id: 55, name: "Silent Hill 2", image: "https://via.placeholder.com/250x350?text=Silent+Hill+2", platform: "Console", genre: "Horror", studio: "Konami" },
  { id: 56, name: "Dark Souls 3", image: "https://via.placeholder.com/250x350?text=Dark+Souls+3", platform: "PC", genre: "RPG", studio: "FromSoftware" },
  { id: 57, name: "Sekiro", image: "https://via.placeholder.com/250x350?text=Sekiro", platform: "PC", genre: "RPG", studio: "FromSoftware" },
  { id: 58, name: "Bloodborne", image: "https://via.placeholder.com/250x350?text=Bloodborne", platform: "Console", genre: "RPG", studio: "FromSoftware" },
  { id: 59, name: "Monster Hunter World", image: "https://via.placeholder.com/250x350?text=Monster+Hunter", platform: "PC", genre: "Action", studio: "Capcom" },
  { id: 60, name: "Dragon Ball FighterZ", image: "https://via.placeholder.com/250x350?text=DBFZ", platform: "Console", genre: "Fighting", studio: "Arc System Works" },

  { id: 61, name: "Tekken 8", image: "https://via.placeholder.com/250x350?text=Tekken+8", platform: "PC", genre: "Fighting", studio: "Bandai Namco" },
  { id: 62, name: "Mortal Kombat 11", image: "https://via.placeholder.com/250x350?text=MK11", platform: "Console", genre: "Fighting", studio: "NetherRealm Studios" },
  { id: 63, name: "Street Fighter 6", image: "https://via.placeholder.com/250x350?text=SF6", platform: "Console", genre: "Fighting", studio: "Capcom" },
  { id: 64, name: "Smash Bros Ultimate", image: "https://via.placeholder.com/250x350?text=Smash+Ultimate", platform: "Console", genre: "Fighting", studio: "Nintendo" },
  { id: 65, name: "ARMS", image: "https://via.placeholder.com/250x350?text=ARMS", platform: "Console", genre: "Fighting", studio: "Nintendo" },

  { id: 66, name: "Animal Crossing", image: "https://via.placeholder.com/250x350?text=Animal+Crossing", platform: "Console", genre: "Simulation", studio: "Nintendo" },
  { id: 67, name: "Kirby and the Forgotten Land", image: "https://via.placeholder.com/250x350?text=Kirby", platform: "Console", genre: "Adventure", studio: "HAL Laboratory" },
  { id: 68, name: "Splatoon 3", image: "https://via.placeholder.com/250x350?text=Splatoon+3", platform: "Console", genre: "Shooter", studio: "Nintendo" },
  { id: 69, name: "Mario Kart 8 Deluxe", image: "https://via.placeholder.com/250x350?text=Mario+Kart+8", platform: "Console", genre: "Racing", studio: "Nintendo" },
  { id: 70, name: "Super Mario Odyssey", image: "https://via.placeholder.com/250x350?text=Mario+Odyssey", platform: "Console", genre: "Adventure", studio: "Nintendo" },

  { id: 71, name: "Zelda: Tears of the Kingdom", image: "https://via.placeholder.com/250x350?text=Zelda+TotK", platform: "Console", genre: "Adventure", studio: "Nintendo" },
  { id: 72, name: "Pokemon Scarlet", image: "https://via.placeholder.com/250x350?text=Pokemon+Scarlet", platform: "Console", genre: "RPG", studio: "Game Freak" },
  { id: 73, name: "Pokemon Violet", image: "https://via.placeholder.com/250x350?text=Pokemon+Violet", platform: "Console", genre: "RPG", studio: "Game Freak" },
  { id: 74, name: "Mario Party Superstars", image: "https://via.placeholder.com/250x350?text=Mario+Party", platform: "Console", genre: "Party", studio: "NDcube" },
  { id: 75, name: "Luigi’s Mansion 3", image: "https://via.placeholder.com/250x350?text=Luigi+Mansion+3", platform: "Console", genre: "Adventure", studio: "Next Level Games" },

  { id: 76, name: "Hitman 3", image: "https://via.placeholder.com/250x350?text=Hitman+3", platform: "PC", genre: "Stealth", studio: "IO Interactive" },
  { id: 77, name: "Metal Gear Solid V", image: "https://via.placeholder.com/250x350?text=MGSV", platform: "PC", genre: "Stealth", studio: "Kojima Productions" },
  { id: 78, name: "Assassin’s Creed Valhalla", image: "https://via.placeholder.com/250x350?text=AC+Valhalla", platform: "Console", genre: "RPG", studio: "Ubisoft Montreal" },
  { id: 79, name: "Far Cry 6", image: "https://via.placeholder.com/250x350?text=Far+Cry+6", platform: "Console", genre: "Shooter", studio: "Ubisoft Toronto" },
  { id: 80, name: "Watch Dogs Legion", image: "https://via.placeholder.com/250x350?text=Watch+Dogs", platform: "PC", genre: "Action", studio: "Ubisoft Toronto" },


  { id: 81, name: "No Man’s Sky", image: "https://via.placeholder.com/250x350?text=No+Mans+Sky", platform: "PC", genre: "Adventure", studio: "Hello Games" },
  { id: 82, name: "Subnautica", image: "https://via.placeholder.com/250x350?text=Subnautica", platform: "PC", genre: "Survival", studio: "Unknown Worlds Entertainment" },
  { id: 83, name: "The Forest", image: "https://via.placeholder.com/250x350?text=The+Forest", platform: "PC", genre: "Survival", studio: "Endnight Games" },
  { id: 84, name: "Sons of the Forest", image: "https://via.placeholder.com/250x350?text=Sons+of+the+Forest", platform: "PC", genre: "Survival", studio: "Endnight Games" },
  { id: 85, name: "DayZ", image: "https://via.placeholder.com/250x350?text=DayZ", platform: "PC", genre: "Survival", studio: "Bohemia Interactive" },

  { id: 86, name: "Factorio", image: "https://via.placeholder.com/250x350?text=Factorio", platform: "PC", genre: "Strategy", studio: "Wube Software" },
  { id: 87, name: "Cities: Skylines", image: "https://via.placeholder.com/250x350?text=Cities+Skylines", platform: "PC", genre: "Simulation", studio: "Colossal Order" },
  { id: 88, name: "Planet Zoo", image: "https://via.placeholder.com/250x350?text=Planet+Zoo", platform: "PC", genre: "Simulation", studio: "Frontier Developments" },
  { id: 89, name: "Civilization VI", image: "https://via.placeholder.com/250x350?text=Civilization+VI", platform: "PC", genre: "Strategy", studio: "Firaxis Games" },
  { id: 90, name: "Age of Empires IV", image: "https://via.placeholder.com/250x350?text=AoE4", platform: "PC", genre: "Strategy", studio: "Relic Entertainment" },

  { id: 91, name: "Hades", image: "https://via.placeholder.com/250x350?text=Hades", platform: "PC", genre: "Rogue-like", studio: "Supergiant Games" },
  { id: 92, name: "Hollow Knight", image: "https://via.placeholder.com/250x350?text=Hollow+Knight", platform: "PC", genre: "Adventure", studio: "Team Cherry" },
  { id: 93, name: "Cuphead", image: "https://via.placeholder.com/250x350?text=Cuphead", platform: "PC", genre: "Action", studio: "Studio MDHR" },
  { id: 94, name: "Ori and the Will of the Wisps", image: "https://via.placeholder.com/250x350?text=Ori", platform: "PC", genre: "Adventure", studio: "Moon Studios" },
  { id: 95, name: "Celeste", image: "https://via.placeholder.com/250x350?text=Celeste", platform: "PC", genre: "Platformer", studio: "Matt Makes Games" },

  { id: 96, name: "Geometry Dash", image: "https://via.placeholder.com/250x350?text=Geometry+Dash", platform: "Mobile", genre: "Arcade", studio: "RobTop Games" },
  { id: 97, name: "Subway Surfers", image: "https://via.placeholder.com/250x350?text=Subway+Surfers", platform: "Mobile", genre: "Arcade", studio: "Kiloo & SYBO Games" },
  { id: 98, name: "Temple Run 2", image: "https://via.placeholder.com/250x350?text=Temple+Run+2", platform: "Mobile", genre: "Runner", studio: "Imangi Studios" },
  { id: 99, name: "Plants vs Zombies", image: "https://via.placeholder.com/250x350?text=PvZ", platform: "Mobile", genre: "Strategy", studio: "PopCap Games" },
  { id: 100, name: "Candy Crush Saga", image: "https://via.placeholder.com/250x350?text=Candy+Crush", platform: "Mobile", genre: "Puzzle", studio: "King" }
];
